#!/usr/bin/env node
'use strict';
const path = require('path');
const { spawn } = require('child_process');

process.title = process.argv[2];

const forever = spawn(path.resolve(__dirname, 'forever'));

console.log(forever.pid);
