#!/usr/bin/env node
'use strict';
const { spawn } = require('child_process');

if (process.argv[2]) {
	process.title = process.argv[2];
}

const forever = spawn('node', ['-e', 'setTimeout(function () {}, 20000)']);

console.log(forever.pid);
